### ISSUE TITLE
roo 2.7.1 has bugs

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/modsulator#20]
Tests will fail when you upgrade modsulator's roo to use the latest version (2.7.1 as of today). For example, it seems to ignore the first content row of spec/fixtures/crowdsourcing_bridget_1.xlsx.

**Comment by jcoyne** [comment]
@tingulfsen have you opened an issue on the Roo repo for this?

**Comment by tingulfsen** [comment]
No I have not.

If you have some time, it might be worth checking that the latest version of Roo will require changes.

**Comment by jcoyne** [comment]
There haven't been any updates to roo since 2.7.1

**Comment by jcoyne** [comment]
We tested this (`rake spec`) on both roo 2.7.1 and `master@8f65109` and both had the same 3 errors:
```
Failed examples:

rspec ./spec/features/process_template_spec.rb:13 # Modsulator initialized loads sample test file in Excel Workbook format correctly
rspec ./spec/features/modsulator_sheet_unit_spec.rb:9 # ModsulatorSheet#rows should present each row as a hash
rspec ./spec/features/modsulator_sheet_unit_spec.rb:5 # ModsulatorSheet#rows should use the right header row
```
