### ISSUE TITLE
Allow metadata upload when dor_object is in a "registered" state

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/modsulator#9]
modsulator currently does not support spreadsheet upload when an object is in a "registered" state. Tommy pointed to the piece of code where in_accession is defined - and it seems that there are numerical state definitions that are included for the broad category of "in accessioning".

@LynnMcRae - this is in keeping with your understanding of the desired functionality, correct?

**Comment by tingulfsen** [comment]
Fixed by sul-dlss/argo#510
